import type { CSSProperties } from "react";
import type { RoomStatus } from "./lib/types";

export const FONT = "'Manrope', -apple-system, BlinkMacSystemFont, sans-serif";
export const MONO = "'JetBrains Mono', 'SF Mono', monospace";
export const TOP_BAR_CLEARANCE = 96;
export const BOTTOM_BAR_CLEARANCE = 96;
export const SIDE_PANEL_TOP_INSET = 16;
export const ATLAS_THEME_VARS = {
  dark: {
    "--atlas-bg": "#060e1e",
    "--atlas-glass": "rgba(10,26,59,.5)",
    "--atlas-glass-heavy": "rgba(5,11,24,.97)",
    "--atlas-chrome-surface": "rgba(120,170,255,.09)",
    "--atlas-chrome-surface-soft": "rgba(100,150,255,.055)",
    "--atlas-chrome-surface-strong": "rgba(140,185,255,.15)",
    "--atlas-panel-surface": "rgba(100,150,255,.07)",
    "--atlas-panel-surface-soft": "rgba(80,130,255,.035)",
    "--atlas-panel-surface-strong": "rgba(140,185,255,.17)",
    "--atlas-border": "rgba(120,170,255,.17)",
    "--atlas-border-strong": "rgba(140,190,255,.30)",
    "--atlas-text": "#e6eeff",
    "--atlas-sec": "rgba(200,218,255,.72)",
    "--atlas-muted": "rgba(170,196,245,.44)",
    "--atlas-accent": "#3dc8ff",
    "--atlas-accent-bg": "rgba(61,200,255,.15)",
    "--atlas-accent-bg-faint": "rgba(61,200,255,.06)",
    "--atlas-accent-border": "rgba(61,200,255,.36)",
    "--atlas-hover-surface": "rgba(120,170,255,.09)",
    "--atlas-focus-surface": "rgba(61,200,255,.13)",
    "--atlas-btn-surface": "rgba(120,165,255,.08)",
    "--atlas-btn-surface-hover": "rgba(140,180,255,.12)",
    "--atlas-btn-surface-active": "rgba(61,200,255,.15)",
    "--atlas-btn-primary-bg": "rgba(61,200,255,.18)",
    "--atlas-btn-primary-bg-hover": "rgba(61,200,255,.28)",
    "--atlas-btn-primary-text": "#90e4ff",
    "--atlas-control-shadow": "inset 0 1px 0 rgba(160,200,255,.12), 0 1px 4px rgba(0,4,18,.32)",
    "--atlas-elev-top": "0 4px 16px rgba(0,4,20,.38), 0 12px 36px rgba(0,4,20,.28)",
    "--atlas-elev-bottom": "0 -2px 28px rgba(0,4,20,.32)",
    "--atlas-elev-drawer": "0 8px 36px rgba(0,4,20,.44)",
    "--atlas-elev-side": "-8px 0 28px rgba(0,4,20,.32)",
    "--atlas-elev-floating": "0 4px 12px rgba(0,4,20,.34), 0 8px 24px rgba(0,4,20,.26)",
    "--atlas-elev-accent": "inset 0 0 0 1px rgba(61,200,255,.18)",
    "--atlas-elev-accent-active": "inset 0 0 0 1px rgba(61,200,255,.34)",
    "--atlas-status-available": "#2fd68e",
    "--atlas-status-available-bg": "rgba(47,214,142,.12)",
    "--atlas-status-available-border": "rgba(47,214,142,.26)",
    "--atlas-status-available-band": "rgba(47,214,142,.18)",
    "--atlas-status-occupied": "#f96b6b",
    "--atlas-status-occupied-bg": "rgba(249,107,107,.12)",
    "--atlas-status-occupied-border": "rgba(249,107,107,.26)",
    "--atlas-status-occupied-band": "rgba(249,107,107,.20)",
    "--atlas-status-focus": "#f9c030",
    "--atlas-status-focus-bg": "rgba(249,192,48,.12)",
    "--atlas-status-focus-border": "rgba(249,192,48,.26)",
    "--atlas-status-focus-band": "rgba(249,192,48,.18)",
    "--atlas-status-offline": "#7e95b8",
    "--atlas-status-offline-bg": "rgba(126,149,184,.09)",
    "--atlas-status-offline-border": "rgba(126,149,184,.18)",
    "--atlas-status-offline-band": "rgba(126,149,184,.12)",
    "--atlas-scrollbar-thumb": "rgba(120,160,255,.14)",
    "--atlas-panel-blur": "blur(24px) saturate(180%)",
    "--atlas-overlay": "rgba(0,4,18,.14)",
  },
  light: {
    "--atlas-bg": "#f0f4f7",
    "--atlas-glass": "rgba(250,252,254,.82)",
    "--atlas-glass-heavy": "rgba(255,255,255,.98)",
    "--atlas-chrome-surface": "rgba(255,255,255,.96)",
    "--atlas-chrome-surface-soft": "rgba(250,252,254,.82)",
    "--atlas-chrome-surface-strong": "rgba(255,255,255,.99)",
    "--atlas-panel-surface": "rgba(240,244,247,.82)",
    "--atlas-panel-surface-soft": "rgba(235,241,246,.64)",
    "--atlas-panel-surface-strong": "rgba(255,255,255,.94)",
    "--atlas-border": "rgba(16,44,66,.12)",
    "--atlas-border-strong": "rgba(16,44,66,.22)",
    "--atlas-text": "#0d1f2e",
    "--atlas-sec": "rgba(13,31,46,.78)",
    "--atlas-muted": "rgba(13,31,46,.48)",
    "--atlas-accent": "#0775b5",
    "--atlas-accent-bg": "rgba(7,117,181,.10)",
    "--atlas-accent-bg-faint": "rgba(7,117,181,.04)",
    "--atlas-accent-border": "rgba(7,117,181,.24)",
    "--atlas-hover-surface": "rgba(13,38,60,.06)",
    "--atlas-focus-surface": "rgba(7,117,181,.10)",
    "--atlas-btn-surface": "rgba(255,255,255,.96)",
    "--atlas-btn-surface-hover": "#ffffff",
    "--atlas-btn-surface-active": "rgba(7,117,181,.09)",
    "--atlas-btn-primary-bg": "rgba(7,117,181,.12)",
    "--atlas-btn-primary-bg-hover": "rgba(7,117,181,.20)",
    "--atlas-btn-primary-text": "#0775b5",
    "--atlas-control-shadow": "inset 0 1px 0 rgba(255,255,255,.80), 0 1px 4px rgba(10,28,46,.10)",
    "--atlas-elev-top": "0 2px 12px rgba(10,28,46,.10), 0 8px 32px rgba(10,28,46,.10)",
    "--atlas-elev-bottom": "0 -1px 12px rgba(10,28,46,.08)",
    "--atlas-elev-drawer": "0 8px 32px rgba(10,28,46,.12)",
    "--atlas-elev-side": "-4px 0 16px rgba(10,28,46,.10)",
    "--atlas-elev-floating": "0 2px 8px rgba(10,28,46,.10), 0 6px 20px rgba(10,28,46,.10)",
    "--atlas-elev-accent": "inset 0 0 0 1px rgba(7,117,181,.12)",
    "--atlas-elev-accent-active": "inset 0 0 0 1px rgba(7,117,181,.24)",
    "--atlas-status-available": "#34d399",
    "--atlas-status-available-bg": "rgba(52,211,153,.12)",
    "--atlas-status-available-border": "rgba(52,211,153,.17)",
    "--atlas-status-available-band": "rgba(52,211,153,.18)",
    "--atlas-status-occupied": "#f87171",
    "--atlas-status-occupied-bg": "rgba(248,113,113,.12)",
    "--atlas-status-occupied-border": "rgba(248,113,113,.17)",
    "--atlas-status-occupied-band": "rgba(248,113,113,.20)",
    "--atlas-status-focus": "#fbbf24",
    "--atlas-status-focus-bg": "rgba(251,191,36,.12)",
    "--atlas-status-focus-border": "rgba(251,191,36,.17)",
    "--atlas-status-focus-band": "rgba(251,191,36,.18)",
    "--atlas-status-offline": "#64748b",
    "--atlas-status-offline-bg": "rgba(100,116,139,.10)",
    "--atlas-status-offline-border": "rgba(100,116,139,.15)",
    "--atlas-status-offline-band": "rgba(100,116,139,.14)",
    "--atlas-scrollbar-thumb": "rgba(16,44,66,.14)",
    "--atlas-panel-blur": "blur(100px) saturate(140%)",
    "--atlas-overlay": "rgba(10,28,46,.04)",
  },
} as const;
export const T = {
  bg: "var(--atlas-bg)",
  glass: "var(--atlas-glass)",
  glassH: "var(--atlas-glass-heavy)",
  border: "var(--atlas-border)",
  borderH: "var(--atlas-border-strong)",
  text: "var(--atlas-text)",
  sec: "var(--atlas-sec)",
  muted: "var(--atlas-muted)",
  accent: "var(--atlas-accent)",
  accentBg: "var(--atlas-accent-bg)",
  accentBorder: "var(--atlas-accent-border)",
  accentBgFaint: "var(--atlas-accent-bg-faint)",
  btnSurface: "var(--atlas-btn-surface)",
  btnSurfaceHover: "var(--atlas-btn-surface-hover)",
  btnSurfaceActive: "var(--atlas-btn-surface-active)",
  btnSurfaceBorder: "var(--atlas-border-strong)",
  btnPrimaryBg: "var(--atlas-btn-primary-bg)",
  btnPrimaryBgHover: "var(--atlas-btn-primary-bg-hover)",
  btnPrimaryText: "var(--atlas-btn-primary-text)",
  controlShadow: "var(--atlas-control-shadow)",
  elevTop: "var(--atlas-elev-top)",
  elevBottom: "var(--atlas-elev-bottom)",
  elevDrawer: "var(--atlas-elev-drawer)",
  elevSide: "var(--atlas-elev-side)",
  elevFloating: "var(--atlas-elev-floating)",
  elevAccent: "var(--atlas-elev-accent)",
  elevAccentActive: "var(--atlas-elev-accent-active)",
  overlay: "var(--atlas-overlay)",
  chromeSurface: "var(--atlas-chrome-surface)",
  chromeSurfaceSoft: "var(--atlas-chrome-surface-soft)",
  chromeSurfaceStrong: "var(--atlas-chrome-surface-strong)",
  panelSurface: "var(--atlas-panel-surface)",
  panelSurfaceSoft: "var(--atlas-panel-surface-soft)",
  panelSurfaceStrong: "var(--atlas-panel-surface-strong)",
  controlBorder: "1px solid var(--atlas-border)",
  controlBorderStrong: "1px solid var(--atlas-border-strong)",
  statusAvailable: "var(--atlas-status-available)",
  statusAvailableBg: "var(--atlas-status-available-bg)",
  statusAvailableBorder: "var(--atlas-status-available-border)",
  statusAvailableBand: "var(--atlas-status-available-band)",
  statusOccupied: "var(--atlas-status-occupied)",
  statusOccupiedBg: "var(--atlas-status-occupied-bg)",
  statusOccupiedBorder: "var(--atlas-status-occupied-border)",
  statusOccupiedBand: "var(--atlas-status-occupied-band)",
  statusFocus: "var(--atlas-status-focus)",
  statusFocusBg: "var(--atlas-status-focus-bg)",
  statusFocusBorder: "var(--atlas-status-focus-border)",
  statusFocusBand: "var(--atlas-status-focus-band)",
  statusOffline: "var(--atlas-status-offline)",
  statusOfflineBg: "var(--atlas-status-offline-bg)",
  statusOfflineBorder: "var(--atlas-status-offline-border)",
  statusOfflineBand: "var(--atlas-status-offline-band)",
  scrollbarThumb: "var(--atlas-scrollbar-thumb)",
  panelBlur: "var(--atlas-panel-blur)",
};

export const ST: Record<RoomStatus, { c: string; bg: string; border: string; band: string; label: string }> = {
  available: { c: T.statusAvailable, bg: T.statusAvailableBg, border: T.statusAvailableBorder, band: T.statusAvailableBand, label: "Свободно" },
  occupied: { c: T.statusOccupied, bg: T.statusOccupiedBg, border: T.statusOccupiedBorder, band: T.statusOccupiedBand, label: "Занято" },
  focus: { c: T.statusFocus, bg: T.statusFocusBg, border: T.statusFocusBorder, band: T.statusFocusBand, label: "Фокус" },
  offline: { c: T.statusOffline, bg: T.statusOfflineBg, border: T.statusOfflineBorder, band: T.statusOfflineBand, label: "Не в сети" },
};

export const CONTROL_HEIGHT = 42;
export const ACTION_HEIGHT = 40;
export const ACTION_RADIUS = 0;
export const CONTROL_INNER_HEIGHT = 34;
export const segmentedFrame: CSSProperties = {
  display: "flex",
  alignItems: "center",
  gap: 4,
  padding: 4,
  minHeight: CONTROL_HEIGHT,
  background: T.chromeSurface,
  border: T.controlBorder,
  boxShadow: T.controlShadow,
};
export const segmentedButtonBase: CSSProperties = {
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  gap: 6,
  minWidth: 0,
  minHeight: CONTROL_INNER_HEIGHT,
  padding: "0 12px",
  background: T.chromeSurfaceSoft,
  border: "1px solid transparent",
  borderRadius: 0,
  fontSize: 12,
  fontWeight: 600,
  fontFamily: FONT,
  color: T.muted,
  whiteSpace: "nowrap",
};
export const segmentedButtonActive: CSSProperties = {
  color: T.accent,
  background: T.accentBg,
  border: T.controlBorder,
  boxShadow: `inset 0 0 0 1px ${T.accentBorder}`,
};
export const utilityControlBase: CSSProperties = {
  display: "inline-flex",
  alignItems: "center",
  minHeight: CONTROL_HEIGHT,
  padding: "0 14px",
  borderRadius: 0,
  background: T.chromeSurface,
  border: T.controlBorder,
  boxShadow: T.controlShadow,
};
export const secondaryActionBase: CSSProperties = {
  display: "inline-flex",
  alignItems: "center",
  justifyContent: "center",
  gap: 8,
  minHeight: ACTION_HEIGHT,
  padding: "0 14px",
  background: T.btnSurface,
  color: T.text,
  border: `1px solid ${T.btnSurfaceBorder}`,
  borderRadius: ACTION_RADIUS,
  fontSize: 12,
  fontWeight: 700,
  fontFamily: FONT,
  letterSpacing: ".01em",
  boxShadow: T.controlShadow,
};
export const primaryActionBase: CSSProperties = {
  display: "inline-flex",
  alignItems: "center",
  justifyContent: "center",
  gap: 8,
  minHeight: ACTION_HEIGHT,
  padding: "0 16px",
  background: T.btnPrimaryBg,
  color: T.btnPrimaryText,
  border: `1px solid ${T.accentBorder}`,
  borderRadius: ACTION_RADIUS,
  fontSize: 12,
  fontWeight: 700,
  fontFamily: FONT,
  letterSpacing: ".01em",
  boxShadow: `${T.controlShadow}, ${T.elevAccent}`,
};
export const chromeSectionBase: CSSProperties = {
  background: T.panelSurface,
  border: T.controlBorder,
  boxShadow: T.controlShadow,
};
export const chromeSectionStrongBase: CSSProperties = {
  ...chromeSectionBase,
  background: T.panelSurfaceStrong,
};
export const glassChromeBase: CSSProperties = {
  background: T.glass,
  backdropFilter: "blur(28px) saturate(150%)",
  WebkitBackdropFilter: "blur(28px) saturate(150%)",
};
export const glassSidePanelBase: CSSProperties = {
  position: "absolute",
  top: TOP_BAR_CLEARANCE + SIDE_PANEL_TOP_INSET,
  right: 0,
  bottom: BOTTOM_BAR_CLEARANCE,
  borderRadius: 0,
  display: "flex",
  flexDirection: "column",
  ...glassChromeBase,
  borderLeft: T.controlBorderStrong,
  boxShadow: T.elevSide,
  overflow: "hidden",
};
export const strongSectionHeaderBase: CSSProperties = {
  background: T.panelSurfaceStrong,
  borderBottom: T.controlBorderStrong,
  flexShrink: 0,
};
export const strongSectionFooterBase: CSSProperties = {
  background: T.panelSurfaceStrong,
  borderTop: T.controlBorderStrong,
  flexShrink: 0,
};
export const monoSectionKickerBase: CSSProperties = {
  fontSize: 10,
  fontWeight: 700,
  fontFamily: MONO,
  textTransform: "uppercase",
  letterSpacing: ".06em",
};
export const mutedSectionLabelBase: CSSProperties = {
  ...monoSectionKickerBase,
  color: T.muted,
};
export const microChipBase: CSSProperties = {
  display: "inline-flex",
  alignItems: "center",
  minHeight: 28,
  padding: "0 10px",
  fontSize: 11,
  fontWeight: 700,
  color: T.sec,
  background: T.chromeSurface,
  border: T.controlBorder,
  borderRadius: 0,
  letterSpacing: ".01em",
};

export const CSS = `
  @import url('https://fonts.googleapis.com/css2?family=Manrope:wght@300;400;500;600;700;800&family=JetBrains+Mono:wght@400;500&display=swap');
  *{box-sizing:border-box;margin:0;padding:0}
  ::placeholder{color:${T.muted}}
  select{-webkit-appearance:none;-moz-appearance:none;appearance:none}
  ::-webkit-scrollbar{width:5px}::-webkit-scrollbar-track{background:transparent}::-webkit-scrollbar-thumb{background:${T.scrollbarThumb};border-radius:5px}
  @keyframes oa-fade{from{opacity:0}to{opacity:1}}
  @keyframes oa-slide-up{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}
  @keyframes oa-slide-out{from{opacity:1;transform:translateY(0)}to{opacity:0;transform:translateY(10px)}}
  @keyframes oa-slide-left{from{opacity:0;transform:translateX(14px)}to{opacity:1;transform:translateX(0)}}
  @keyframes oa-pulse{0%,100%{opacity:1}50%{opacity:.35}}
  @keyframes card-in{from{opacity:0;transform:translateY(5px)}to{opacity:1;transform:translateY(0)}}
  .card-anim{animation:card-in 200ms ease-out both;animation-delay:calc(var(--ci,0)*14ms)}
  .oa-fade{animation:oa-fade .18s ease-out}
  .oa-slide-up{animation:oa-slide-up .22s ease-out}
  .oa-slide-out{animation:oa-slide-out .2s ease-in both}
  .oa-slide-left{animation:oa-slide-left .2s ease-out}
`;

export const S: Record<string, CSSProperties> = {
  shell: { position: "relative", width: "100%", height: "100vh", overflow: "hidden", fontFamily: FONT, color: T.text, fontSize: 13, background: T.bg, lineHeight: 1.5 },
  mapBg: { position: "absolute", inset: 0, zIndex: 0 },
  mapLoading: { width: "100%", height: "100%", display: "flex", alignItems: "center", justifyContent: "center", color: T.sec },
  emptyState: { width: "100%", height: "100vh", display: "flex", alignItems: "center", justifyContent: "center", background: T.bg, color: T.sec, fontFamily: FONT },
  topBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
    display: "grid",
    gridTemplateColumns: "1fr",
    alignItems: "stretch",
    gap: 0,
    padding: 0,
    ...glassChromeBase,
    borderBottom: T.controlBorderStrong,
    borderRadius: 0,
    minHeight: TOP_BAR_CLEARANCE,
  },
  topBrandBlock: { display: "grid", gap: 8, minWidth: 0, padding: "12px 14px" },
  mapControls: {
    position: "absolute",
    top: TOP_BAR_CLEARANCE + 12,
    right: 12,
    zIndex: 8,
    display: "flex",
    flexDirection: "column",
    gap: 6,
    alignItems: "stretch",
    padding: 8,
    ...glassChromeBase,
    border: T.controlBorderStrong,
    boxShadow: T.elevTop,
  },
  mapControlsHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingBottom: 2,
  },
  mapControlsToggle: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 22,
    height: 22,
    background: "none",
    border: "none",
    color: T.muted,
    flexShrink: 0,
    padding: 0,
  },
  mapControlsRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  topBrandRow: { display: "flex", alignItems: "center", gap: 10, minWidth: 0 },
  topSectionLabel: { ...monoSectionKickerBase, color: T.sec },
  logo: { display: "flex", alignItems: "center", gap: 8, padding: "0 12px", minHeight: CONTROL_HEIGHT, background: T.chromeSurface, border: T.controlBorder, boxShadow: T.controlShadow, borderRadius: 0, flexShrink: 0 },
  searchField: { display: "flex", alignItems: "center", gap: 10, padding: "0 14px", borderRadius: 0, fontFamily: FONT, fontSize: 13, fontWeight: 500, color: T.sec, background: T.chromeSurface, border: T.controlBorder, boxShadow: T.controlShadow, minWidth: 320, minHeight: CONTROL_HEIGHT, flex: 1 },
  searchInput: { flex: 1, minWidth: 0, background: "none", border: "none", outline: "none", color: T.text, fontSize: 13, fontWeight: 500, fontFamily: FONT },
  searchClearBtn: { width: 24, height: 24, display: "flex", alignItems: "center", justifyContent: "center", background: T.chromeSurface, border: "1px solid transparent", borderRadius: 0, color: T.muted, flexShrink: 0 },
  kbd: { marginLeft: "auto", padding: "0 8px", minHeight: 24, display: "inline-flex", alignItems: "center", fontSize: 10, fontWeight: 600, fontFamily: MONO, color: T.muted, background: T.chromeSurfaceSoft, borderRadius: 0, border: T.controlBorder },
  topSceneBlock: { display: "grid", alignContent: "center", gap: 8, padding: "12px 14px", borderRight: T.controlBorder, minWidth: 280, background: T.chromeSurfaceSoft },
  topActionBlock: { display: "grid", alignContent: "center", gap: 8, padding: "12px 14px", minWidth: 420, background: T.chromeSurfaceSoft },
  topActionRow: { display: "flex", alignItems: "stretch", justifyContent: "flex-end", gap: 8, flexWrap: "nowrap" },
  topFloorGroup: { ...segmentedFrame },
  themeSwitch: { display: "flex", gap: 2, padding: 3, borderRadius: 0, background: T.chromeSurfaceSoft, border: T.controlBorder },
  themeBtn: { padding: "7px 12px", background: "none", border: "none", borderRadius: 0, fontSize: 12, fontWeight: 600, fontFamily: FONT, color: T.muted },
  themeBtnActive: { color: T.text, background: T.chromeSurfaceStrong },
  viewModes: { ...segmentedFrame, width: "100%" },
  segmentBtn: { ...segmentedButtonBase },
  segmentBtnEqual: { flex: "1 1 0" },
  segmentBtnMono: { fontFamily: MONO, fontWeight: 700, letterSpacing: ".01em" },
  segmentBtnActive: { ...segmentedButtonActive },
  opsBtn: { ...utilityControlBase, gap: 8, fontFamily: FONT, color: T.sec },
  opsBadge: { display: "flex", alignItems: "center", gap: 5, fontSize: 11, fontWeight: 600, whiteSpace: "nowrap" },
  syncChip: { ...utilityControlBase, gap: 7, padding: "0 12px", fontSize: 10, fontFamily: MONO, color: T.sec, whiteSpace: "nowrap", letterSpacing: ".04em" },
  liveDot: { width: 7, height: 7, borderRadius: "50%", flexShrink: 0, animation: "oa-pulse 2.5s ease infinite" },
  bottomBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 10,
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "stretch",
    gap: 0,
    padding: 0,
    background: "var(--atlas-glass)",
    backdropFilter: "blur(32px) saturate(190%)",
    WebkitBackdropFilter: "blur(32px) saturate(190%)",
    borderTop: "1px solid var(--atlas-border-strong)",
    borderRadius: 0,
    minHeight: BOTTOM_BAR_CLEARANCE,
    boxShadow: T.elevBottom,
  },
  bottomBarDrawerOpen: {},
  bottomModuleLabel: {
    fontSize: 10,
    lineHeight: 1,
    fontWeight: 700,
    fontFamily: MONO,
    color: T.muted,
    textTransform: "uppercase",
    letterSpacing: ".1em",
  },
  bottomContextBlock: {
    display: "flex",
    alignItems: "stretch",
    width: "100%",
    minWidth: 0,
    minHeight: BOTTOM_BAR_CLEARANCE,
    padding: 0,
    background: "transparent",
    border: "none",
    borderRight: "1px solid var(--atlas-border)",
    textAlign: "left",
    overflow: "hidden",
  },
  bottomContextBlockDrawerOpen: {},
  bottomContextBlockSolo: {
    borderRight: "none",
  },
  bottomContextStrip: {
    display: "block",
    width: 3,
    alignSelf: "stretch",
    flexShrink: 0,
    background: `linear-gradient(180deg, var(--atlas-accent) 0%, transparent 100%)`,
    opacity: 0.55,
  },
  bottomExpandArrow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 48,
    flexShrink: 0,
    color: "var(--atlas-accent)",
    background: "transparent",
    opacity: 0.7,
  },
  bottomExpandArrowDrawerOpen: {
    opacity: 1,
  },
  bottomActionPrimary: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
    minHeight: BOTTOM_BAR_CLEARANCE,
    padding: "0 16px",
    background: "transparent",
  },
  bottomRouteActions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
    minHeight: BOTTOM_BAR_CLEARANCE,
    padding: "0 16px",
    background: "transparent",
  },
  bottomRouteActionsDrawerOpen: {},
  bottomSecondaryGroup: {
    display: "flex",
    alignItems: "center",
    background: "var(--atlas-btn-surface)",
    border: "1px solid var(--atlas-border-strong)",
    borderRadius: ACTION_RADIUS,
    boxShadow: T.controlShadow,
    overflow: "hidden",
  },
  bottomSegBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    minHeight: ACTION_HEIGHT,
    padding: "0 14px",
    background: "transparent",
    color: T.text,
    border: "none",
    borderRadius: 0,
    fontSize: 12,
    fontWeight: 600,
    fontFamily: FONT,
    letterSpacing: ".01em",
    whiteSpace: "nowrap",
  },
  bottomPrimaryBtn: {
    ...primaryActionBase,
    padding: "0 20px",
    whiteSpace: "nowrap",
  },
  bottomContext: { display: "grid", minWidth: 0, flex: 1, padding: "14px 16px", alignContent: "center" },
  bottomContextContent: { display: "flex", flexDirection: "column", gap: 4, animation: "oa-fade .15s ease-out", minWidth: 0 },
  bottomHeadline: {
    fontSize: 16,
    fontWeight: 700,
    letterSpacing: "-.018em",
    color: T.text,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  bottomMetaRow: { display: "flex", alignItems: "center", gap: 6, flexWrap: "wrap" },
  bottomMeta: { fontSize: 11.5, color: T.sec, fontWeight: 500 },
  bottomChip: { ...microChipBase, padding: "0 8px", fontSize: 10, fontWeight: 700, fontFamily: MONO, textTransform: "uppercase" },
  bottomActionLabel: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    whiteSpace: "nowrap",
  },
  bottomActionText: {
    fontWeight: 600,
    letterSpacing: ".01em",
    lineHeight: 1,
  },
  bottomActionGlyph: {
    width: 15,
    height: 15,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    color: T.sec,
    background: "none",
    border: "none",
    boxShadow: "none",
  },
  bottomActionGlyphAccent: {
    color: T.btnPrimaryText,
    background: "none",
    border: "none",
    boxShadow: "none",
  },
  floorPicker: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 4 },
  zoomStack: { ...segmentedFrame },
  zoomBtn: {
    width: 36,
    minHeight: CONTROL_HEIGHT,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "none",
    border: "1px solid transparent",
    fontSize: 17,
    fontWeight: 400,
    fontFamily: FONT,
    color: T.sec,
  },
  zoomDivider: { width: 1, height: 22, background: T.border },
  fab: { ...primaryActionBase, whiteSpace: "nowrap" },
  fabActive: { background: T.btnPrimaryBgHover, border: `1px solid ${T.accentBorder}`, boxShadow: `${T.controlShadow}, ${T.elevAccentActive}` },
  searchDrawerLayer: {
    position: "absolute",
    top: TOP_BAR_CLEARANCE,
    right: 0,
    bottom: BOTTOM_BAR_CLEARANCE,
    left: 0,
    zIndex: 9,
    background: T.overlay,
    display: "flex",
    alignItems: "stretch",
    justifyContent: "stretch",
    padding: 0,
  },
  searchDrawerSheet: {
    width: "100%",
    height: "100%",
    minHeight: 0,
    maxHeight: "none",
    borderRadius: 0,
    overflow: "hidden",
    boxShadow: T.elevDrawer,
  },
  drawerLayer: {
    position: "absolute",
    top: TOP_BAR_CLEARANCE - 1,
    right: 0,
    bottom: BOTTOM_BAR_CLEARANCE,
    left: 0,
    zIndex: 9,
    background: T.overlay,
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "stretch",
    padding: 0,
  },
  drawerLayerWorkspace: {
    alignItems: "stretch",
  },
  drawerLayerInfo: {
    alignItems: "flex-end",
  },
  drawerLayerInfoInteractive: {
    pointerEvents: "none",
    background: "transparent",
  },
  drawerSheet: {
    width: "100%",
    minHeight: 0,
    borderRadius: 0,
    overflow: "hidden",
    boxShadow: T.elevDrawer,
    display: "flex",
    flexDirection: "column",
    background: T.glass,
    backdropFilter: T.panelBlur,
    WebkitBackdropFilter: T.panelBlur,
  },
  drawerSheetWorkspace: {
    height: "100%",
    maxHeight: "none",
    borderTop: "none",
    borderRight: "none",
    borderBottom: "none",
    borderLeft: "none",
  },
  drawerSheetInfo: {
    height: "auto",
    maxHeight: `calc(100vh - ${TOP_BAR_CLEARANCE + BOTTOM_BAR_CLEARANCE}px)`,
    pointerEvents: "auto",
    borderTop: T.controlBorderStrong,
    borderRight: "none",
    borderBottom: "none",
    borderLeft: "none",
  },
  browsePanel: {
    width: "100%",
    height: "100%",
    maxWidth: "none",
    borderRadius: 0,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  bpHeader: { padding: "10px 12px", borderBottom: T.controlBorderStrong, flexShrink: 0, background: T.panelSurfaceStrong },
  bpDivider: { width: 1, height: 20, background: T.border },
  bpBody: { flex: 1, overflowY: "auto", padding: "12px 16px 16px", display: "flex", flexDirection: "column", gap: 12 },
  bpPeopleSection: { display: "grid", gap: 8 },
  bpSectionTitle: { display: "flex", alignItems: "center", gap: 6, fontSize: 11, fontWeight: 700, color: T.sec, textTransform: "uppercase", letterSpacing: ".06em" },
  bpPeopleGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(260px,1fr))", gap: 8 },
  pill: { ...microChipBase, padding: "0 12px", minHeight: 30, fontSize: 11, fontWeight: 600, color: T.sec, fontFamily: FONT },
  pillActive: { ...segmentedButtonActive },
  pillSm: { ...microChipBase, padding: "0 10px", minHeight: 26, fontSize: 10, fontWeight: 600, color: T.muted, fontFamily: FONT },
  pillSmActive: { ...segmentedButtonActive },
  groupedGrid: { display: "flex", flexDirection: "column", gap: 12 },
  group: { display: "flex", flexDirection: "column", gap: 8 },
  groupHeader: { display: "flex", alignItems: "center", gap: 8 },
  groupLabel: { fontSize: 12, fontWeight: 700, color: T.sec, textTransform: "uppercase", letterSpacing: ".04em" },
  groupCount: { fontSize: 10, fontWeight: 600, color: T.muted, background: T.chromeSurfaceSoft, padding: "1px 7px", borderRadius: 10 },
  grid: { display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(200px,1fr))", gap: 8 },
  gridCompact: { gridTemplateColumns: "repeat(auto-fill,minmax(170px,1fr))", gap: 8 },
  card: { display: "flex", flexDirection: "column", gap: 8, padding: "12px", background: T.panelSurfaceStrong, border: T.controlBorder, boxShadow: T.controlShadow, borderRadius: 0, textAlign: "left", fontFamily: FONT, color: T.text },
  cardSelected: { border: `1px solid ${T.accent}`, background: T.accentBg, boxShadow: `0 0 0 1px ${T.accent}40` },
  cardTop: { display: "flex", justifyContent: "space-between", alignItems: "flex-start" },
  cardNameRow: { display: "flex", alignItems: "center", gap: 7 },
  statusDot: { width: 7, height: 7, borderRadius: "50%", flexShrink: 0 },
  cardName: { fontSize: 13, fontWeight: 700, lineHeight: 1.3 },
  cardLevel: { fontSize: 10, fontWeight: 700, fontFamily: MONO, color: T.accent, background: T.accentBg, padding: "2px 6px", borderRadius: 0, flexShrink: 0 },
  cardBottom: { display: "flex", alignItems: "center", gap: 8 },
  cardKind: { fontSize: 11, color: T.muted, fontWeight: 500 },
  cardCap: { display: "flex", alignItems: "center", gap: 4, fontSize: 11, color: T.sec, fontWeight: 500 },
  cardDept: { fontSize: 10, color: T.muted, fontWeight: 500, marginTop: -2 },
  routeChoiceGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(220px,1fr))", gap: 10 },
  routeChoiceCard: { display: "flex", flexDirection: "column", gap: 10, padding: "12px 14px", background: T.panelSurfaceStrong, border: T.controlBorder, boxShadow: T.controlShadow, borderRadius: 0, textAlign: "left", fontFamily: FONT, color: T.text, minHeight: 108 },
  routeChoiceCardSelected: { border: `1px solid ${T.accent}`, background: T.accentBg, boxShadow: `0 0 0 1px ${T.accent}40` },
  routeChoiceTop: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 10 },
  routeChoiceNameRow: { display: "flex", alignItems: "center", gap: 7, minWidth: 0 },
  routeChoiceName: { fontSize: 13, fontWeight: 700, lineHeight: 1.3, minWidth: 0 },
  routeChoiceMeta: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" },
  routeChoiceMetaText: { display: "inline-flex", alignItems: "center", gap: 4, fontSize: 11, color: T.sec, fontWeight: 500 },
  routeChoiceFooter: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10, marginTop: "auto" },
  routeChoiceDept: { fontSize: 10, color: T.muted, fontWeight: 500 },
  routeChoiceStatus: { fontSize: 10, padding: "2px 8px", flexShrink: 0 },
  personRow: { display: "flex", alignItems: "center", gap: 10, padding: "10px 12px", background: T.panelSurface, border: T.controlBorder, boxShadow: T.controlShadow, borderRadius: 0, fontFamily: FONT, color: T.text, textAlign: "left" },
  personAv: { width: 30, height: 30, borderRadius: "50%", background: `linear-gradient(135deg,${T.accentBg},${T.accentBgFaint})`, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 12, fontWeight: 700, color: T.accent, flexShrink: 0 },
  personInfo: { flex: 1, display: "flex", flexDirection: "column", gap: 1, minWidth: 0 },
  routePanel: {
    width: "100%",
    height: "100%",
    maxWidth: "none",
    borderRadius: 0,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    padding: 0,
    background: "transparent",
  },
  rpTopStatusChip: {
    ...microChipBase,
    minHeight: 24,
    padding: "0 9px",
    fontSize: 10,
    fontWeight: 700,
    fontFamily: MONO,
    color: T.sec,
    letterSpacing: ".04em",
    textTransform: "uppercase",
  },
  rpTopStatusChipReady: {
    color: ST.available.c,
    background: ST.available.bg,
    border: `1px solid ${ST.available.border}`,
  },
  rpTopStatusChipError: {
    color: ST.occupied.c,
    background: ST.occupied.bg,
    border: `1px solid ${ST.occupied.border}`,
  },
  rpTopAside: { display: "flex", alignItems: "center", justifyContent: "flex-end", gap: 8, minWidth: 0, flexWrap: "wrap" },
  rpTopActions: { display: "flex", alignItems: "stretch", justifyContent: "flex-end", gap: 8, flexShrink: 0, flexWrap: "wrap", minWidth: 0 },
  rpTopToggle: {
    ...secondaryActionBase,
    minHeight: 34,
    padding: "0 11px",
    gap: 6,
    fontSize: 10,
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  rpTopToggleActive: {
    color: T.accent,
    background: T.accentBg,
    border: `1px solid ${T.accentBorder}`,
    boxShadow: `inset 0 0 0 1px ${T.accent}1f`,
  },
  rpFlowStep: { ...microChipBase, padding: "0 12px", minHeight: 30, gap: 6, fontSize: 11, fontWeight: 700, color: T.sec, fontFamily: FONT },
  rpFlowStepActive: { ...segmentedButtonActive },
  rpFlowStepReady: { color: ST.available.c, fontSize: 12, lineHeight: 1, marginTop: -1 },
  rpFlowShell: { flex: 1, display: "flex", flexDirection: "column", gap: 12, minHeight: 0, overflow: "hidden", padding: "10px 14px 14px" },
  rpPlannerBar: { display: "grid", gridTemplateColumns: "minmax(0,1fr) 36px minmax(0,1fr)", gap: 10, alignItems: "stretch", flexShrink: 0, minWidth: 0, padding: 8, background: T.panelSurface, border: T.controlBorder, boxShadow: T.controlShadow },
  rpPlannerCard: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    minHeight: 74,
    padding: "12px 14px",
    background: T.chromeSurface,
    border: T.controlBorder,
    boxShadow: "none",
    minWidth: 0,
    cursor: "pointer",
  },
  rpPlannerCardActive: { background: T.panelSurfaceStrong, border: `1px solid ${T.accentBorder}`, boxShadow: `inset 0 0 0 1px ${T.accent}1f` },
  rpPlannerRow: { display: "flex", alignItems: "center", gap: 12, minWidth: 0 },
  rpPlannerGlyph: {
    width: 30,
    height: 30,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: T.muted,
    flexShrink: 0,
    background: T.chromeSurfaceSoft,
    border: T.controlBorder,
  },
  rpPlannerGlyphActive: { color: T.accent },
  rpPlannerBody: { display: "grid", gap: 3, minWidth: 0, flex: 1 },
  rpPlannerLabel: { fontSize: 10, fontWeight: 700, color: T.muted, letterSpacing: ".07em", fontFamily: MONO, lineHeight: 1 },
  rpPlannerName: { fontSize: 15, fontWeight: 700, letterSpacing: "-.02em", lineHeight: 1.2, color: T.text, minWidth: 0, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  rpPlannerNameEmpty: { fontSize: 15, fontWeight: 600, letterSpacing: "-.02em", lineHeight: 1.2, color: T.muted, minWidth: 0 },
  rpPlannerHint: { fontSize: 11, color: T.muted, lineHeight: 1.35, minWidth: 0 },
  rpSummaryPanel: { display: "grid", gap: 10, alignContent: "start", minHeight: 152, padding: "14px 16px", background: T.panelSurface, border: T.controlBorder, boxShadow: T.controlShadow, minWidth: 0 },
  rpSwapDock: { display: "flex", alignItems: "center", justifyContent: "center" },
  rpStage: { display: "flex", flexDirection: "column", minWidth: 0, minHeight: 0, background: T.panelSurface, border: T.controlBorder, boxShadow: T.controlShadow },
  rpStageTitle: { fontSize: 15, fontWeight: 800, letterSpacing: "-.02em", lineHeight: 1.2, marginTop: 0 },
  rpStageStat: { ...microChipBase, padding: "0 9px", minHeight: 26, fontSize: 10, fontWeight: 700, color: T.sec, fontFamily: MONO, letterSpacing: ".04em", flexShrink: 0 },
  rpStageControls: { display: "flex", alignItems: "center", gap: 10, padding: "12px 14px", borderBottom: T.controlBorder, flexShrink: 0, background: T.chromeSurface },
  browseStageControls: { gap: 12, flexWrap: "wrap" },
  browseStageComment: { fontSize: 11, lineHeight: 1.45, color: T.muted, minWidth: 0, flex: 1 },
  rpStageControlsRoute: { alignItems: "center", gap: 12, flexWrap: "wrap" },
  rpStageSearchRow: { display: "flex", alignItems: "center", gap: 12, minWidth: 0, flex: 1, flexWrap: "wrap" },
  rpStageMetaRow: { display: "flex", alignItems: "center", justifyContent: "flex-end", gap: 10, minWidth: 0, flexWrap: "wrap", marginLeft: "auto" },
  rpStageBody: { flex: 1, overflowY: "auto", padding: "10px 14px 14px", minHeight: 0, scrollPaddingBottom: 18 },
  rpAside: { display: "flex", flexDirection: "column", gap: 12, minHeight: 0 },
  rpAsideShell: { display: "flex", flexDirection: "column", background: T.panelSurface, border: T.controlBorder, boxShadow: T.controlShadow, minHeight: 0 },
  rpAsideSection: { display: "flex", flexDirection: "column", gap: 12, padding: "14px 16px", borderBottom: T.controlBorderStrong },
  rpAsideSectionActive: { background: T.accentBg },
  rpAsideSectionLast: { borderBottom: "none" },
  rpColumns: {
    flex: 1,
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) 40px minmax(0, 1fr)",
    gap: 12,
    overflow: "hidden",
    minHeight: 0,
  },
  rpCol: {
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    minWidth: 0,
    background: T.panelSurface,
    border: T.controlBorder,
    boxShadow: T.controlShadow,
  },
  rpColLast: { borderRight: T.controlBorder },
  rpColHeader: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    padding: "10px 14px",
    borderBottom: T.controlBorder,
    flexShrink: 0,
    background: T.panelSurfaceStrong,
  },
  rpColLabel: { ...mutedSectionLabelBase, marginBottom: 2 },
  rpSelected: { display: "flex", alignItems: "center", gap: 7, padding: "0 10px", minHeight: 30, background: T.accentBg, border: `1px solid ${T.accentBorder}`, boxShadow: `inset 0 0 0 1px ${T.accent}1f`, borderRadius: 0, marginTop: 0 },
  rpSelectedName: { fontSize: 13, fontWeight: 650 },
  rpSelectedLevel: { fontSize: 10, fontWeight: 700, fontFamily: MONO, color: T.accent, marginLeft: "auto" },
  rpClearBtn: { width: 22, height: 22, display: "flex", alignItems: "center", justifyContent: "center", background: T.chromeSurface, border: "1px solid transparent", borderRadius: 0, color: T.muted, marginLeft: 4, flexShrink: 0 },
  rpColSearch: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flex: 1,
    minWidth: 0,
    padding: 0,
    borderBottom: "none",
    color: T.muted,
    flexShrink: 0,
    background: "transparent",
  },
  rpColInput: { flex: 1, background: "none", border: "none", outline: "none", color: T.text, fontSize: 12, fontFamily: FONT },
  rpColToolbar: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    flexShrink: 0,
    flexWrap: "nowrap",
    padding: 0,
    background: "transparent",
  },
  rpColBody: { flex: 1, overflowY: "auto", padding: "14px", scrollPaddingBottom: 18 },
  rpEmptyState: { display: "grid", gap: 6, padding: "12px 14px", background: T.panelSurface, border: T.controlBorder },
  rpEmptyTitle: { fontSize: 13, fontWeight: 700, color: T.text },
  rpStepCard: { display: "flex", flexDirection: "column", gap: 5, color: T.text, textAlign: "left" },
  rpStepClearBtn: { width: 22, height: 22, display: "flex", alignItems: "center", justifyContent: "center", background: T.chromeSurfaceSoft, border: T.controlBorder, color: T.muted, padding: 0, flexShrink: 0 },
  rpStepCardActive: { background: "transparent" },
  rpStepCardTop: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10 },
  rpActiveStateChip: { ...microChipBase, minWidth: 72, padding: "0 10px", minHeight: 24, fontSize: 10, fontWeight: 700, color: T.sec, justifyContent: "center", fontFamily: FONT },
  rpActiveStateChipHidden: { visibility: "hidden" },
  rpStepCardBody: { display: "grid", gap: 4 },
  rpStepCardName: { fontSize: 13, fontWeight: 700, lineHeight: 1.2, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  rpStepCardPlaceholder: { fontSize: 11, color: T.muted, lineHeight: 1.4 },
  rpStepCardMeta: { display: "flex", alignItems: "center", gap: 4, flexWrap: "wrap" },
  rpStepCardActions: { display: "flex", alignItems: "center", justifyContent: "flex-start", gap: 8, flexWrap: "wrap", paddingTop: 2 },
  rpStepAction: { minHeight: 26, padding: "0 9px", fontSize: 10 },
  rpStepMiniChip: { ...microChipBase, padding: "0 7px", minHeight: 22, fontSize: 10, fontWeight: 700, fontFamily: MONO, color: T.sec, letterSpacing: ".03em" },
  rpSummaryCard: { display: "grid", gap: 10 },
  rpSummaryPath: { display: "flex", alignItems: "center", gap: 8, fontSize: 12, color: T.text, fontWeight: 600, lineHeight: 1.45, flexWrap: "wrap" },
  rpSummaryMetaRow: { display: "flex", alignItems: "center", gap: 6, flexWrap: "wrap" },
  rpSwapCol: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    position: "relative",
    background: "transparent",
    paddingTop: 92,
    overflow: "hidden",
    flexShrink: 0,
  },
  rpSwapBtn: {
    width: 28,
    height: 28,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: T.chromeSurfaceSoft,
    border: T.controlBorder,
    boxShadow: "none",
    borderRadius: 0,
    color: T.sec,
    position: "relative",
    zIndex: 1,
  },
  drawerInfoPanel: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    background: "transparent",
  },
  infoDrawerHeader: {
    ...strongSectionHeaderBase,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "12px 16px",
  },
  infoDrawerHeaderMain: {
    display: "grid",
    gap: 4,
    minWidth: 0,
  },
  infoDrawerHeaderTitle: {
    fontSize: 17,
    fontWeight: 800,
    letterSpacing: "-.02em",
    lineHeight: 1.2,
    color: T.text,
    minWidth: 0,
  },
  drawerSectionGrid: { display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", gap: 12 },
  drawerSectionGridSingle: { display: "grid", gridTemplateColumns: "minmax(0,1fr)", gap: 12 },
  sidePanelSectionFull: { gridColumn: "1 / -1" },
  rpFooter: {
    ...strongSectionFooterBase,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    padding: "12px 16px",
  },
  rpFooterSummary: { display: "grid", gap: 3, minWidth: 0 },
  rpFooterHeadline: {
    fontSize: 15,
    fontWeight: 800,
    letterSpacing: "-.02em",
    color: T.text,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  rpFooterMeta: { fontSize: 11, color: T.sec },
  rpFooterActions: { display: "flex", alignItems: "center", justifyContent: "flex-end", gap: 10, flexWrap: "wrap" },
  rpResult: { padding: "16px 20px", borderTop: T.controlBorder, flexShrink: 0, display: "flex", gap: 20, alignItems: "flex-start", flexWrap: "wrap" },
  rrHero: { display: "flex", alignItems: "center", gap: 14, flex: "1 1 400px", flexWrap: "wrap" },
  rrIcon: { width: 42, height: 42, borderRadius: 0, background: T.accentBg, color: T.accent, border: `1px solid ${T.accentBorder}`, boxShadow: `inset 0 0 0 1px ${T.accent}1f`, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },
  rrMain: { display: "flex", flexDirection: "column" },
  rrDist: { fontSize: 22, fontWeight: 800, fontFamily: MONO, letterSpacing: "-.02em" },
  rrTime: { fontSize: 11, color: T.sec },
  rrPath: { display: "flex", alignItems: "center", gap: 6, fontSize: 11, color: T.sec, fontWeight: 500, width: "100%" },
  rrStats: { display: "flex", gap: 16, marginTop: 4, width: "100%" },
  rrStat: { display: "flex", flexDirection: "column", alignItems: "center", gap: 1 },
  rrStatV: { fontSize: 15, fontWeight: 800, fontFamily: MONO, lineHeight: 1, display: "flex", alignItems: "center" },
  rrStatL: { fontSize: 9, fontWeight: 600, color: T.muted, textTransform: "uppercase", letterSpacing: ".05em" },
  rrDirections: { flex: "1 1 300px", display: "flex", flexDirection: "column", gap: 0 },
  rrStep: { display: "flex", alignItems: "flex-start", gap: 10, padding: "6px 0", marginBottom: 10 },
  rrStepN: { width: 22, height: 22, borderRadius: 0, background: T.chromeSurface, border: T.controlBorder, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 10, fontWeight: 700, flexShrink: 0, color: T.sec },
  rrStepT: { fontSize: 12, color: T.sec, lineHeight: 1.5, paddingTop: 2 },
  rrStepsGrid: { display: "grid", gap: 20, alignItems: "start" },
  rrStepsColumn: { display: "grid", alignContent: "start", gap: 0, minWidth: 0 },
  accentBtn: { ...primaryActionBase },
  ghostBtn: { ...secondaryActionBase },
  iconBtn: { width: 30, height: 30, display: "flex", alignItems: "center", justifyContent: "center", background: T.chromeSurface, border: T.controlBorder, boxShadow: T.controlShadow, borderRadius: 0, color: T.sec, flexShrink: 0 },
  detailFloat: { ...glassSidePanelBase, zIndex: 20, width: 352 },
  routeResultFloat: { ...glassSidePanelBase, zIndex: 22, width: 416 },
  opsStatusPillContent: { display: "inline-flex", alignItems: "center", gap: 5, lineHeight: 1 },
  opsStatusPillDot: { width: 6, height: 6, minWidth: 6, borderRadius: "50%", display: "block", flexShrink: 0 },
  statusPill: { display: "inline-flex", alignItems: "center", gap: 5, padding: "3px 10px", fontSize: 11, fontWeight: 600, borderRadius: 20 },
  opsPanel: { ...glassSidePanelBase, zIndex: 40, width: 372 },
  checkRow: { display: "flex", alignItems: "center", gap: 7, cursor: "pointer", userSelect: "none", fontSize: 12, color: T.sec, fontWeight: 500 },
  checkBox: { width: 15, height: 15, borderRadius: 4, border: `1.5px solid ${T.borderH}`, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", transition: "all .12s", color: T.bg, flexShrink: 0 },
  checkBoxOn: { background: T.accent, border: `1.5px solid ${T.accent}` },
  rrStatsPanel: { display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", gap: 8 },
  rrStatCard: { ...chromeSectionStrongBase, display: "flex", flexDirection: "column", gap: 4, padding: "10px 12px" },
  opsShellBody: {
    padding: "14px 16px 16px",
  },
  opsWorkspacePanel: {
    width: "100%",
    height: "100%",
    maxWidth: "none",
    borderRadius: 0,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    background: "transparent",
  },
  opsWorkspaceToolbar: {
    display: "grid",
    gridTemplateColumns: "minmax(0,1fr) auto",
    alignItems: "center",
    gap: 14,
  },
  opsWorkspaceToolbarMain: {
    display: "grid",
    gap: 4,
    minWidth: 0,
  },
  opsWorkspaceToolbarMeta: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
    flexWrap: "wrap",
  },
  opsWorkspaceBody: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    overflow: "hidden",
    padding: "10px 14px 14px",
  },
  opsShell: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    background: "transparent",
    border: "none",
    boxShadow: "none",
    overflow: "hidden",
    flex: 1,
    minHeight: 0,
  },
  opsShellHero: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: "12px",
    background: T.panelSurface,
    border: T.controlBorder,
    boxShadow: T.controlShadow,
    flexShrink: 0,
  },
  opsHeroSummaryRow: {
    display: "grid",
    gridTemplateColumns: "minmax(180px, .72fr) minmax(0, 1.28fr)",
    gap: 8,
    alignItems: "stretch",
  },
  opsSelectorStage: {
    flex: 1,
    minHeight: 0,
  },
  opsHeroMetricCard: {
    display: "grid",
    gap: 4,
    padding: "10px 12px",
    background: `linear-gradient(135deg, ${T.accentBg} 0%, ${T.accentBgFaint} 100%)`,
    border: `1px solid ${T.accentBorder}`,
    boxShadow: `inset 0 0 0 1px ${T.accent}14`,
  },
  opsHeroMetricValueRow: {
    display: "flex",
    alignItems: "baseline",
    gap: 8,
  },
  opsHeroMetricValue: {
    fontSize: 34,
    fontWeight: 800,
    fontFamily: MONO,
    lineHeight: 1,
    letterSpacing: "-.02em",
  },
  opsHeroMetricUnit: {
    fontSize: 10,
    fontWeight: 700,
    color: T.muted,
    letterSpacing: ".06em",
    textTransform: "uppercase",
  },
  opsHeroMetricSubtext: {
    fontSize: 10,
    color: T.sec,
    fontWeight: 500,
  },
  opsMetricsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: 8,
  },
  opsMetricItem: {
    display: "grid",
    gap: 2,
    padding: "9px 10px",
    background: T.panelSurfaceSoft,
    border: T.controlBorder,
    textAlign: "center",
    alignContent: "center",
  },
  opsMetricLabel: {
    fontSize: 9,
    fontWeight: 700,
    color: T.muted,
    letterSpacing: ".05em",
  },
  opsMetricValue: {
    fontSize: 22,
    fontWeight: 800,
    fontFamily: MONO,
    lineHeight: 1,
  },
  opsShellHeroTop: {
    display: "grid",
    gridTemplateColumns: "minmax(240px, .8fr) minmax(0, 1.5fr)",
    gap: 10,
    alignItems: "stretch",
  },
  opsShellLeadCard: {
    ...chromeSectionStrongBase,
    display: "grid",
    gap: 8,
    padding: "12px 14px",
    minWidth: 0,
  },
  opsShellLeadValueRow: {
    display: "flex",
    alignItems: "flex-end",
    gap: 14,
    minWidth: 0,
  },
  opsShellLeadMeta: {
    display: "grid",
    gap: 6,
    paddingBottom: 2,
    minWidth: 0,
  },
  opsShellHeroSummary: {
    ...chromeSectionStrongBase,
    display: "grid",
    gap: 10,
    padding: "12px 14px",
    minWidth: 0,
  },
  opsShellHeroFacts: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: 8,
  },
  opsShellFact: {
    ...chromeSectionBase,
    display: "grid",
    gap: 4,
    padding: "10px 12px",
    minWidth: 0,
  },
  opsShellFactLabel: {
    fontSize: 9,
    fontWeight: 700,
    color: T.muted,
    textTransform: "uppercase",
    letterSpacing: ".06em",
  },
  opsShellFactValue: {
    fontSize: 18,
    fontWeight: 800,
    fontFamily: MONO,
    lineHeight: 1,
    color: T.text,
  },
  opsShellHeroBar: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    flexWrap: "wrap",
  },
  opsShellHeroMeta: {
    display: "grid",
    gap: 6,
    minWidth: 0,
  },
  opsShellLiveTag: {
    ...microChipBase,
    minHeight: 26,
    padding: "0 10px",
    fontSize: 10,
    fontWeight: 700,
    fontFamily: MONO,
    color: T.sec,
    letterSpacing: ".04em",
    whiteSpace: "nowrap",
  },
  opsShellMetricRail: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: 8,
  },
  opsLevelRail: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))",
    gap: 10,
  },
  opsLevelCard: {
    ...chromeSectionBase,
    display: "grid",
    gap: 10,
    padding: "12px 14px",
    textAlign: "left",
    color: T.text,
    fontFamily: FONT,
  },
  opsLevelCardActive: {
    border: `1px solid ${T.accentBorder}`,
    background: T.accentBg,
    boxShadow: `0 0 0 1px ${T.accent}24`,
  },
  opsLevelCardTop: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  opsLevelCardBody: {
    display: "grid",
    gap: 4,
  },
  opsLevelCardValue: {
    fontSize: 26,
    fontWeight: 800,
    fontFamily: MONO,
    lineHeight: 1,
  },
  opsLevelCardMeta: {
    fontSize: 11,
    color: T.sec,
    fontWeight: 500,
  },
  opsLevelCardStats: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
  },
  opsLevelCardStat: {
    ...microChipBase,
    padding: "0 8px",
    minHeight: 22,
    fontSize: 10,
    fontWeight: 700,
    color: T.sec,
    fontFamily: MONO,
  },
  opsShellSection: {
    ...chromeSectionBase,
    display: "flex",
    flexDirection: "column",
    gap: 12,
    padding: "12px 14px",
    minWidth: 0,
  },
  opsShellSectionWide: {
    background: T.panelSurface,
  },
  opsShellSectionIntro: {
    display: "flex",
    alignItems: "center",
    minHeight: 18,
  },
  opsLevelGroupStack: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  opsLevelGroup: {
    display: "grid",
    gap: 10,
  },
  opsLevelGroupHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    flexWrap: "wrap",
  },
  opsLevelGroupTitleRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
  },
  opsLevelBadge: {
    ...microChipBase,
    padding: "0 9px",
    minHeight: 24,
    fontSize: 10,
    fontWeight: 700,
    color: T.accent,
    fontFamily: MONO,
    background: T.accentBg,
    border: `1px solid ${T.accentBorder}`,
  },
  opsLevelGroupTitle: {
    fontSize: 12,
    fontWeight: 700,
    color: T.sec,
    letterSpacing: ".01em",
  },
  opsOverviewGrid: { display: "grid", gridTemplateColumns: "minmax(0,1.7fr) minmax(320px,.95fr)", gap: 12, alignItems: "stretch" },
  opsHeroCard: { ...chromeSectionBase, display: "flex", flexDirection: "column", gap: 12, padding: "14px 16px", minHeight: 0 },
  opsHeroMain: { display: "flex", alignItems: "flex-start", gap: 16 },
  opsHeroMetricBlock: { display: "grid", gap: 4, minWidth: 108, flexShrink: 0 },
  opsHeroMetric: { fontSize: 42, fontWeight: 800, fontFamily: MONO, letterSpacing: "-.04em", lineHeight: 0.95 },
  opsHeroMetricLabel: { ...mutedSectionLabelBase, fontFamily: FONT },
  opsHeroCopy: { display: "grid", gap: 4, minWidth: 0, paddingTop: 2 },
  opsHeroTitle: { fontSize: 16, fontWeight: 800, letterSpacing: "-.02em", color: T.text },
  opsBreakdownBar: { display: "grid", gridTemplateColumns: "repeat(4,minmax(0,1fr))", gap: 8 },
  opsBreakdownSegment: { display: "grid", gap: 3, padding: "8px 12px", minWidth: 0, minHeight: 50, alignContent: "center", boxShadow: T.controlShadow },
  opsBreakdownValue: { fontSize: 14, fontWeight: 800, fontFamily: MONO, lineHeight: 1 },
  opsBreakdownLabel: { fontSize: 9, fontWeight: 700, color: "currentColor", textTransform: "uppercase", letterSpacing: ".05em", opacity: 0.9 },
  opsMetaRow: { display: "grid", gridTemplateColumns: "repeat(3,minmax(0,1fr))", gap: 8 },
  opsMetaCard: { ...chromeSectionStrongBase, display: "grid", gap: 4, padding: "10px 12px" },
  opsMetaLabel: { fontSize: 9, fontWeight: 700, color: T.muted, textTransform: "uppercase", letterSpacing: ".06em" },
  opsMetaValue: { fontSize: 18, fontWeight: 800, fontFamily: MONO, letterSpacing: "-.03em", lineHeight: 1 },
  opsStatusGrid: { display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", gap: 8 },
  opsStatusCard: { ...chromeSectionStrongBase, display: "grid", gap: 6, padding: "12px 14px", minHeight: 92, alignContent: "space-between" },
  opsStatusValue: { fontSize: 26, fontWeight: 800, fontFamily: MONO, lineHeight: 1 },
  opsStatusLabel: { ...mutedSectionLabelBase, fontFamily: FONT },
  opsRoomGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(260px,1fr))", gap: 10 },
  opsRoomCard: { ...chromeSectionStrongBase, width: "100%", display: "flex", flexDirection: "column", gap: 12, padding: "12px 14px", fontFamily: FONT, color: T.text, textAlign: "left", minHeight: 128 },
  opsRoomCardSelected: { border: `1px solid ${T.accent}`, background: T.accentBg, boxShadow: `0 0 0 1px ${T.accent}40` },
  opsRoomHeader: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 12 },
  opsRoomTitleRow: { display: "flex", alignItems: "center", gap: 8, minWidth: 0 },
  opsRoomName: { fontSize: 14, fontWeight: 700, lineHeight: 1.3, minWidth: 0 },
  opsStatusPill: { marginLeft: "auto", flexShrink: 0, fontSize: 10, padding: "3px 9px" },
  opsRoomMeta: { display: "flex", alignItems: "center", gap: 6, flexWrap: "wrap" },
  opsRoomMetaItem: { ...microChipBase, padding: "0 8px", minHeight: 24, fontSize: 10, fontWeight: 700, color: T.sec, fontFamily: MONO, letterSpacing: ".03em" },
  opsRoomFooter: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, marginTop: "auto" },
  opsRoomDept: { fontSize: 11, color: T.muted, fontWeight: 500, minWidth: 0 },
  opsRoomSignal: { fontSize: 10, fontWeight: 700, color: T.accent, textTransform: "uppercase", letterSpacing: ".05em", flexShrink: 0 },
  floatHeader: { ...strongSectionHeaderBase, display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12, paddingBottom: 12 },
  panelHeaderTight: {
    ...strongSectionHeaderBase,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
    padding: "14px 16px",
  },
  sidePanelBody: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    overflowY: "auto",
    minHeight: 0,
    padding: "14px 16px",
    flex: "0 1 auto",
    maxHeight: `calc(100vh - ${TOP_BAR_CLEARANCE + BOTTOM_BAR_CLEARANCE + 104}px)`,
    background: "transparent",
  },
  sidePanelBodyDetail: {
    paddingTop: 12,
    gap: 8,
  },
  infoPanelScrollArea: {
    maxHeight: 280,
  },
  sidePanelFooter: {
    ...strongSectionFooterBase,
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    padding: "14px 16px",
  },
  sidePanelFooterColumn: {
    ...strongSectionFooterBase,
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: "14px 16px",
  },
  sidePanelTitle: { margin: 0, fontSize: 16, fontWeight: 800, letterSpacing: "-.02em", lineHeight: 1.15 },
  sidePanelSubline: { fontSize: 11, color: T.sec },
  sidePanelSection: { ...chromeSectionBase, display: "flex", flexDirection: "column", gap: 10, padding: "12px 14px" },
  sidePanelSectionCompact: { ...chromeSectionBase, display: "flex", flexDirection: "column", gap: 8, padding: "10px 12px" },
  sidePanelSectionHeader: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8 },
  floatKicker: { fontSize: 10, fontWeight: 700, textTransform: "uppercase", letterSpacing: ".07em", color: T.accent },
  floatTitle: { margin: 0, fontSize: 20, fontWeight: 800, letterSpacing: "-.03em", lineHeight: 1.15 },
  floatSubline: { fontSize: 12, color: T.sec },
  panelInset: { ...chromeSectionStrongBase, display: "flex", flexDirection: "column", gap: 10, padding: "12px 14px" },
  panelInsetAccent: { display: "flex", alignItems: "center", gap: 10, padding: "12px 14px", background: T.accentBg, border: `1px solid ${T.accentBorder}`, boxShadow: `inset 0 0 0 1px ${T.accent}1f`, borderRadius: 0 },
  panelInsetScroll: { overflowY: "auto", padding: "0 0 2px", minHeight: 0, flex: 1 },
  panelSectionLabel: { ...mutedSectionLabelBase },
  panelMetaGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8 },
  panelMetaCell: { ...chromeSectionStrongBase, display: "flex", flexDirection: "column", gap: 3, padding: "10px 12px" },
  panelChipRow: { display: "flex", gap: 6, flexWrap: "wrap" },
  panelActionRow: { display: "flex", gap: 8, flexWrap: "wrap" },
  panelActionColumn: { display: "flex", flexDirection: "column", gap: 8 },
  infoChip: { ...microChipBase, padding: "0 10px", fontSize: 11, fontWeight: 600, color: T.sec },
  detailHeroCard: { ...chromeSectionStrongBase, display: "grid", gap: 12, padding: "14px 16px" },
  detailHeroMain: { display: "flex", alignItems: "flex-start", gap: 12, minWidth: 0 },
  detailHeroGlyph: { width: 38, height: 38, display: "flex", alignItems: "center", justifyContent: "center", background: T.accentBg, border: `1px solid ${T.accentBorder}`, boxShadow: `inset 0 0 0 1px ${T.accent}16`, color: T.accent, fontSize: 11, fontWeight: 700, fontFamily: MONO, flexShrink: 0 },
  detailHeroText: { display: "grid", gap: 8, minWidth: 0, flex: 1 },
  detailHeroTitleRow: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 10, minWidth: 0, flexWrap: "wrap" },
  detailHeroTitle: { fontSize: 16, fontWeight: 800, letterSpacing: "-.02em", lineHeight: 1.2, color: T.text, minWidth: 0 },
  detailHeroSubline: { fontSize: 12, color: T.sec, lineHeight: 1.5 },
  detailMetaGrid: { display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", gap: 8 },
  detailMetaCell: { ...chromeSectionStrongBase, display: "flex", flexDirection: "column", gap: 4, padding: "12px", minWidth: 0 },
  detailMetaLabel: { fontSize: 9, fontWeight: 700, color: T.muted, textTransform: "uppercase", letterSpacing: ".06em" },
  detailMetaValue: { fontSize: 13, fontWeight: 650, color: T.text, lineHeight: 1.35 },
  detailSectionCard: { ...chromeSectionBase, display: "grid", gap: 8, padding: "12px 14px" },
  detailSectionLabel: { ...mutedSectionLabelBase },
  detailSectionText: { fontSize: 13, color: T.text, lineHeight: 1.5, fontWeight: 600 },
  detailEquipmentRow: { display: "flex", alignItems: "center", gap: 6, flexWrap: "wrap" },
  detailStatusBand: { display: "flex", alignItems: "center", gap: 8, padding: "8px 16px", flexShrink: 0 },
  detailStatusDot: { width: 6, height: 6, borderRadius: "50%", flexShrink: 0 },
  detailStatusLbl: { fontSize: 11, fontWeight: 700, textTransform: "uppercase" as const, letterSpacing: ".07em" },
  detailDescBlock: { display: "grid", gap: 6 },
  detailDescText: { fontSize: 14, color: T.text, lineHeight: 1.65, fontWeight: 500 },
  detailMetaCellAccent: { display: "flex", flexDirection: "column", gap: 4, padding: "12px", background: T.accentBg, border: `1px solid ${T.accentBorder}`, boxShadow: T.controlShadow, minWidth: 0 },

  // Search empty state
  emptySearchBlock: { display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: "40px 24px", gap: 8, textAlign: "center" },
  emptySearchIcon: { opacity: 0.45, marginBottom: 2 },
  emptySearchTitle: { fontSize: 15, fontWeight: 700, color: T.sec },
  emptySearchSub: { fontSize: 12, color: T.muted, maxWidth: 260, lineHeight: 1.6 },

  // Route result summary card
  rrSummaryCard: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, padding: "10px 14px", background: T.accentBg, border: `1px solid ${T.accentBorder}`, flexWrap: "wrap" },
  rrSummaryMain: { display: "flex", alignItems: "baseline", gap: 8 },
  rrSummaryDist: { fontSize: 22, fontWeight: 800, fontFamily: MONO, letterSpacing: "-.02em", color: T.text },
  rrSummaryTime: { fontSize: 12, color: T.sec, fontWeight: 500 },
  rrSummaryMeta: { display: "flex", alignItems: "center", gap: 5, flexWrap: "wrap" },
};
